### ISSUE TITLE
Pot Request: Longer Bridges (fixed by EnemyArea)

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#11]
### Steam Workshop Url

https://steamcommunity.com/sharedfiles/filedetails/?id=2565896823&searchtext=

### Repo Url

https://github.com/EnemyArea/ONI-Mods/tree/master/ExtendedBridges

**Comment by DDEle** [comment]
Added (but not translated
713682fe738b0cdb5d152ae10543e85747630ce0
