### ISSUE TITLE
Translation: BuidableNaturalTile

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#2]
### language code

zh-hans

### Mod

BuidableNaturalTile

### File

[BuidableNaturalTile.zip](https://github.com/ONI-Wiki-zh/ONIi18n/files/7792087/BuidableNaturalTile.zip)

**Comment by DDEle** [comment]
Done
8786c5225d65deb46a370df3919326a24337e243
