### ISSUE TITLE
Translation: Automatic Geyser Calculation

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#22]
### language code

zh-hans

### Mod

https://steamcommunity.com/sharedfiles/filedetails/?id=2631833478

### File

 
[automaticgeysercalculation.zip](https://github.com/ONI-Wiki-zh/ONIi18n/files/7932582/automaticgeysercalculation.zip)

**Comment by DDEle** [comment]
Done 👆
