### ISSUE TITLE
Translation: Pliers

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#23]
### language code

zh-hans

### Mod

https://steamcommunity.com/sharedfiles/filedetails/?id=2629866529

### File

 
Pliers （作者：Mayall ）有两个修复模组，Pliers fixed（作者： pt_djefferson(Rus)）、Pliers 2021（作者： Bodzio）
2021多修复了不即时剪断而是复制人操作剪断的选项，这里更新下它多出来的词条
它们所用的类名都是跟原模组一样的‪Pliers.PliersStrings.XXX所以理论上应该是兼容的吧
[zh-hans.zip](https://github.com/ONI-Wiki-zh/ONIi18n/files/7943678/zh-hans.zip)

**Comment by DDEle** [comment]
👆 Done
