### ISSUE TITLE
Translation: PeterHan.PLib.Core.PLibStrings

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#24]
### language code

zh-hans

### Mod

PLib

### File

很多模组都使用了PLib，而PLib.Core中的词条翻译并没有跟随PLib的更新而更新，
同时其中有些词条还引用的游戏系统的词条翻译。
因为这是一个对广大中文玩家影响广泛的东西，因此建议由翻译模组先行提供PLib.Core.PLibStrings的翻译更新。
我同时会提交给PeterHan，但是等到他采纳、再其它mod作者把自己模组中的引用更新上，那会是一个非常非常漫长的时间。
[PeterHan.PLib.Core.PLibStrings.zip](https://github.com/ONI-Wiki-zh/ONIi18n/files/7944494/PeterHan.PLib.Core.PLibStrings.zip)

**Comment by DDEle** [comment]
Done in c6ea1fd
