### ISSUE TITLE
Translation: 

### ISSUE THREAD

**Issue by Catsbuggy** [ONI-Wiki-zh/ONIi18n#28]
### language code

fr_FR

### Mod

ModI18n

### File

[modi18n_fr_FR.txt](https://github.com/ONI-Wiki-zh/ONIi18n/files/8543751/modi18n_fr_FR.txt)

**Comment by NoMoneyXD** [comment]
Je suis désolé que nous ne l’ayons pas terminé aussi rapidement que possible. Mais maintenant c’est fait !
I'm sorry we didn't finish it as quickly as we can. But now it's done!
