### ISSUE TITLE
Translation: Freezer

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#3]
### language code

zh-hans

### Mod

Freezer

### File

[zh.zip](https://github.com/ONI-Wiki-zh/ONIi18n/files/7792097/zh.zip)

**Comment by DDEle** [comment]
Done 4d5c2833a1033d89b5ebc72fdbc36f61a2f6478f

**Comment by DDEle** [comment]
@Ventulus-lab 
Using the mod generated template (without ModI18n), I found that there are some more strings for this mod.
Please [check it](https://github.com/ONI-Wiki-zh/ONIi18n/blob/main/strings/psyko.freezer/zh-hans.po) and make a PR to translate remaining strings if possible.

**Comment by VentulusCN** [comment]
[zh.zip](https://github.com/ONI-Wiki-zh/ONIi18n/files/7792789/zh.zip)
重新传一下
试试这个，用大冰柜作者自己的Pot，在你的翻译mod里行不行

**Comment by DDEle** [comment]
done 3c97ce34aac8a6506141aacb02be9e311a5f4f79
