### ISSUE TITLE
Translation: Automation Plus

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#43]
### language code

zh-hans

### Mod

https://steamcommunity.com/sharedfiles/filedetails/?id=2661900022

### File

[automationplus.zip](https://github.com/ONI-Wiki-zh/ONIi18n/files/9558171/automationplus.zip)

**Comment by NoMoneyXD** [comment]
↑ Done~

**Comment by Ricardo-Evans** [comment]
It seems the translation is outdated, when loaded, a lot of following log appear in the debug console:
[15:26:26.146] [1] [INFO] TRANSLATION ERROR! The following have missing or mismatched parameters:
        ONI_DenseLogic.DenseLogicStrings.UI.UISIDESCREENS.SIGNALREMAPPER.OUTPUT
