### ISSUE TITLE
Station/refinery building crafting recipe is not included in template

### ISSUE THREAD

**Issue by TerrestrisYE** [ONI-Wiki-zh/ONIi18n#5]
Missing crafting recipe entries for building with choosable recipes like Metal Refinery in the generated temple. 
E.g. Advanced Kiln in Chemical Process.

![image](https://user-images.githubusercontent.com/47734181/147845512-00bba9a3-42af-4e76-b8ac-4ac861b19858.png)

**Comment by DDEle** [comment]
Hi TerrestrisYE, some strigns are just not registed in the strings system of the game and thus can not be translated without modder's suppor. Unfortunately, recipt descriptions are one of them. Another example is the name and description of customized gaysers. There is nothing we can do here as the authors said that his mod won't support translations for agile development.

**Comment by TerrestrisYE** [comment]
> 

Got it, thank you.
