### ISSUE TITLE
Pot Request: GasOverlay

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#8]
### Steam Workshop Url

https://steamcommunity.com/sharedfiles/filedetails/?id=1737859934

### Repo url

https://github.com/EtiamNullam/Etiam-ONI-Modpack

**Comment by DDEle** [comment]
GasOverlay has no translatable strings. Please contact its author if possible.
> OK, I have left a comment on its steam workshop page.
