### ISSUE TITLE
Pot Request: Traffic Visualizer

### ISSUE THREAD

**Issue by Ventulus-lab** [ONI-Wiki-zh/ONIi18n#9]
### Steam Workshop Url

https://steamcommunity.com/sharedfiles/filedetails/?id=2208398090

### Repo Url

https://github.com/asquared31415/ONI-mods/tree/main/src/TrafficVisualizer

**Comment by DDEle** [comment]
TrafficVisualizer has no translatable strings. Please contact its author if possible.
